import 'dart:io';

class Localization {
  static String _currentLanguage = 'en-US';
  
  static final Map<String, Map<String, String>> _translations = {
    'en-US': {
      'selectLanguage': 'Select Language',
      'appTitle': 'AppLimit - Grayscale Controller',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Grayscale Controller',
      'initializing': 'Initializing...',
      'setupTitle': 'Setup Your Device',
      'setupDescription': 'Follow these steps to enable USB debugging on your Android device',
      'steps': 'Steps:',
      'instructions': '1. Open Settings on your phone\n2. Go to About Phone\n3. Tap Build Number 7 times\n4. Go back to Settings > Developer Options\n5. Enable USB Debugging',
      'watchTutorial': 'Watch Video Tutorial',
      'continue': 'Continue',
      'detectTitle': 'Connect Your Device',
      'detectWaiting': 'Waiting for device connection...',
      'detectConnected': 'Device connected successfully!',
      'processTitle': 'Applying Grayscale',
      'processing': 'Processing...',
      'start': 'Start',
      'successTitle': 'Success!',
      'successMessage': 'Grayscale mode enabled on your device',
      'successDetail': 'You can now use AppLimit with grayscale display',
      'done': 'Done',
      'appNotInstalled': 'App Not Installed',
      'installAppPrompt': 'AppLimit app is not installed on your device. Would you like to install it?',
      'cancel': 'Cancel',
      'install': 'Install',
    },
    'he-IL': {
      'selectLanguage': 'בחר שפה',
      'appTitle': 'AppLimit - בקר גווני אפור',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'בקר גווני אפור',
      'initializing': 'מאתחל...',
      'setupTitle': 'הגדרת המכשיר שלך',
      'setupDescription': 'עקוב אחר השלבים הבאים כדי להפעיל ניפוי באגים USB במכשיר Android שלך',
      'steps': 'שלבים:',
      'instructions': '1. פתח הגדרות בטלפון\n2. עבור אל אודות הטלפון\n3. הקש על מספר גרסה 7 פעמים\n4. חזור להגדרות > אפשרויות מפתח\n5. הפעל ניפוי באגים USB',
      'watchTutorial': 'צפה בסרטון הדרכה',
      'continue': 'המשך',
      'detectTitle': 'חבר את המכשיר שלך',
      'detectWaiting': 'ממתין לחיבור מכשיר...',
      'detectConnected': 'המכשיר חובר בהצלחה!',
      'processTitle': 'מחיל גווני אפור',
      'processing': 'מעבד...',
      'start': 'התחל',
      'successTitle': 'הצלחה!',
      'successMessage': 'מצב גווני אפור הופעל במכשיר שלך',
      'successDetail': 'עכשיו אתה יכול להשתמש ב-AppLimit עם תצוגת גווני אפור',
      'done': 'סיום',
      'appNotInstalled': 'האפליקציה לא מותקנת',
      'installAppPrompt': 'אפליקציית AppLimit לא מותקנת במכשיר שלך. האם ברצונך להתקין אותה?',
      'cancel': 'ביטול',
      'install': 'התקן',
    },
    'ar-AE': {
      'selectLanguage': 'اختر اللغة',
      'appTitle': 'AppLimit - تحكم التدرج الرمادي',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'تحكم التدرج الرمادي',
      'initializing': 'جاري التهيئة...',
      'setupTitle': 'إعداد جهازك',
      'setupDescription': 'اتبع هذه الخطوات لتمكين تصحيح USB على جهاز Android',
      'steps': 'الخطوات:',
      'instructions': '1. افتح الإعدادات على هاتفك\n2. انتقل إلى حول الهاتف\n3. اضغط على رقم البناء 7 مرات\n4. ارجع إلى الإعدادات > خيارات المطور\n5. قم بتمكين تصحيح USB',
      'watchTutorial': 'شاهد الفيديو التعليمي',
      'continue': 'متابعة',
      'detectTitle': 'قم بتوصيل جهازك',
      'detectWaiting': 'في انتظار اتصال الجهاز...',
      'detectConnected': 'تم توصيل الجهاز بنجاح!',
      'processTitle': 'تطبيق التدرج الرمادي',
      'processing': 'جاري المعالجة...',
      'start': 'ابدأ',
      'successTitle': 'نجح!',
      'successMessage': 'تم تمكين وضع التدرج الرمادي على جهازك',
      'successDetail': 'يمكنك الآن استخدام AppLimit مع عرض التدرج الرمادي',
      'done': 'تم',
      'appNotInstalled': 'التطبيق غير مثبت',
      'installAppPrompt': 'تطبيق AppLimit غير مثبت على جهازك. هل تريد تثبيته؟',
      'cancel': 'إلغاء',
      'install': 'تثبيت',
    },
    'es-ES': {
      'selectLanguage': 'Seleccionar idioma',
      'appTitle': 'AppLimit - Controlador de Escala de Grises',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Controlador de Escala de Grises',
      'initializing': 'Inicializando...',
      'setupTitle': 'Configura tu Dispositivo',
      'setupDescription': 'Sigue estos pasos para habilitar la depuración USB en tu dispositivo Android',
      'steps': 'Pasos:',
      'instructions': '1. Abre Ajustes en tu teléfono\n2. Ve a Acerca del teléfono\n3. Toca Número de compilación 7 veces\n4. Vuelve a Ajustes > Opciones de desarrollador\n5. Habilita Depuración USB',
      'watchTutorial': 'Ver Tutorial en Video',
      'continue': 'Continuar',
      'detectTitle': 'Conecta tu Dispositivo',
      'detectWaiting': 'Esperando conexión del dispositivo...',
      'detectConnected': '¡Dispositivo conectado exitosamente!',
      'processTitle': 'Aplicando Escala de Grises',
      'processing': 'Procesando...',
      'start': 'Iniciar',
      'successTitle': '¡Éxito!',
      'successMessage': 'Modo de escala de grises habilitado en tu dispositivo',
      'successDetail': 'Ahora puedes usar AppLimit con pantalla en escala de grises',
      'done': 'Hecho',
      'appNotInstalled': 'Aplicación no instalada',
      'installAppPrompt': 'La aplicación AppLimit no está instalada en tu dispositivo. ¿Deseas instalarla?',
      'cancel': 'Cancelar',
      'install': 'Instalar',
    },
    'fr-FR': {
      'selectLanguage': 'Sélectionner la langue',
      'appTitle': 'AppLimit - Contrôleur de Niveaux de Gris',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Contrôleur de Niveaux de Gris',
      'initializing': 'Initialisation...',
      'setupTitle': 'Configurez votre Appareil',
      'setupDescription': 'Suivez ces étapes pour activer le débogage USB sur votre appareil Android',
      'steps': 'Étapes:',
      'instructions': '1. Ouvrez Paramètres sur votre téléphone\n2. Allez dans À propos du téléphone\n3. Appuyez sur Numéro de build 7 fois\n4. Retournez dans Paramètres > Options pour les développeurs\n5. Activez Débogage USB',
      'watchTutorial': 'Regarder le Tutoriel Vidéo',
      'continue': 'Continuer',
      'detectTitle': 'Connectez votre Appareil',
      'detectWaiting': 'En attente de connexion de l\'appareil...',
      'detectConnected': 'Appareil connecté avec succès!',
      'processTitle': 'Application des Niveaux de Gris',
      'processing': 'Traitement...',
      'start': 'Démarrer',
      'successTitle': 'Succès!',
      'successMessage': 'Mode niveaux de gris activé sur votre appareil',
      'successDetail': 'Vous pouvez maintenant utiliser AppLimit avec affichage en niveaux de gris',
      'done': 'Terminé',
      'appNotInstalled': 'Application non installée',
      'installAppPrompt': "L'application AppLimit n'est pas installée sur votre appareil. Voulez-vous l'installer ?",
      'cancel': 'Annuler',
      'install': 'Installer',
    },
    'de-DE': {
      'selectLanguage': 'Sprache wählen',
      'appTitle': 'AppLimit - Graustufen-Controller',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Graustufen-Controller',
      'initializing': 'Initialisierung...',
      'setupTitle': 'Richten Sie Ihr Gerät ein',
      'setupDescription': 'Befolgen Sie diese Schritte, um USB-Debugging auf Ihrem Android-Gerät zu aktivieren',
      'steps': 'Schritte:',
      'instructions': '1. Öffnen Sie die Einstellungen auf Ihrem Telefon\n2. Gehen Sie zu Telefoninfo\n3. Tippen Sie 7 Mal auf Build-Nummer\n4. Gehen Sie zurück zu Einstellungen > Entwickleroptionen\n5. Aktivieren Sie USB-Debugging',
      'watchTutorial': 'Video-Tutorial ansehen',
      'continue': 'Weiter',
      'detectTitle': 'Verbinden Sie Ihr Gerät',
      'detectWaiting': 'Warte auf Geräteverbindung...',
      'detectConnected': 'Gerät erfolgreich verbunden!',
      'processTitle': 'Graustufen werden angewendet',
      'processing': 'Verarbeitung...',
      'start': 'Start',
      'successTitle': 'Erfolg!',
      'successMessage': 'Graustufen-Modus auf Ihrem Gerät aktiviert',
      'successDetail': 'Sie können jetzt AppLimit mit Graustufen-Anzeige verwenden',
      'done': 'Fertig',
      'appNotInstalled': 'App nicht installiert',
      'installAppPrompt': 'Die AppLimit-App ist nicht auf Ihrem Gerät installiert. Möchten Sie sie installieren?',
      'cancel': 'Abbrechen',
      'install': 'Installieren',
    },
    'it-IT': {
      'selectLanguage': 'Seleziona lingua',
      'appTitle': 'AppLimit - Controller Scala di Grigi',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Controller Scala di Grigi',
      'initializing': 'Inizializzazione...',
      'setupTitle': 'Configura il tuo Dispositivo',
      'setupDescription': 'Segui questi passaggi per abilitare il debug USB sul tuo dispositivo Android',
      'steps': 'Passaggi:',
      'instructions': '1. Apri Impostazioni sul tuo telefono\n2. Vai su Informazioni telefono\n3. Tocca Numero build 7 volte\n4. Torna a Impostazioni > Opzioni sviluppatore\n5. Abilita Debug USB',
      'watchTutorial': 'Guarda il Tutorial Video',
      'continue': 'Continua',
      'detectTitle': 'Connetti il tuo Dispositivo',
      'detectWaiting': 'In attesa della connessione del dispositivo...',
      'detectConnected': 'Dispositivo connesso con successo!',
      'processTitle': 'Applicazione Scala di Grigi',
      'processing': 'Elaborazione...',
      'start': 'Avvia',
      'successTitle': 'Successo!',
      'successMessage': 'Modalità scala di grigi abilitata sul tuo dispositivo',
      'successDetail': 'Ora puoi usare AppLimit con display in scala di grigi',
      'done': 'Fatto',
      'appNotInstalled': 'App non installata',
      'installAppPrompt': "L'app AppLimit non è installata sul tuo dispositivo. Vuoi installarla?",
      'cancel': 'Annulla',
      'install': 'Installa',
    },
    'pt-BR': {
      'selectLanguage': 'Selecionar idioma',
      'appTitle': 'AppLimit - Controlador de Tons de Cinza',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Controlador de Tons de Cinza',
      'initializing': 'Inicializando...',
      'setupTitle': 'Configure seu Dispositivo',
      'setupDescription': 'Siga estes passos para habilitar a depuração USB no seu dispositivo Android',
      'steps': 'Passos:',
      'instructions': '1. Abra Configurações no seu telefone\n2. Vá para Sobre o telefone\n3. Toque em Número da versão 7 vezes\n4. Volte para Configurações > Opções do desenvolvedor\n5. Habilite Depuração USB',
      'watchTutorial': 'Assistir Tutorial em Vídeo',
      'continue': 'Continuar',
      'detectTitle': 'Conecte seu Dispositivo',
      'detectWaiting': 'Aguardando conexão do dispositivo...',
      'detectConnected': 'Dispositivo conectado com sucesso!',
      'processTitle': 'Aplicando Tons de Cinza',
      'processing': 'Processando...',
      'start': 'Iniciar',
      'successTitle': 'Sucesso!',
      'successMessage': 'Modo tons de cinza ativado no seu dispositivo',
      'successDetail': 'Agora você pode usar o AppLimit com exibição em tons de cinza',
      'done': 'Concluído',
      'appNotInstalled': 'App não instalado',
      'installAppPrompt': 'O app AppLimit não está instalado no seu dispositivo. Gostaria de instalá-lo?',
      'cancel': 'Cancelar',
      'install': 'Instalar',
    },
    'pl-PL': {
      'selectLanguage': 'Wybierz język',
      'appTitle': 'AppLimit - Kontroler Skali Szarości',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Kontroler Skali Szarości',
      'initializing': 'Inicjalizacja...',
      'setupTitle': 'Skonfiguruj swoje Urządzenie',
      'setupDescription': 'Wykonaj te kroki, aby włączyć debugowanie USB na urządzeniu Android',
      'steps': 'Kroki:',
      'instructions': '1. Otwórz Ustawienia na telefonie\n2. Przejdź do Informacje o telefonie\n3. Dotknij Numer kompilacji 7 razy\n4. Wróć do Ustawienia > Opcje programisty\n5. Włącz Debugowanie USB',
      'watchTutorial': 'Obejrzyj Samouczek Wideo',
      'continue': 'Kontynuuj',
      'detectTitle': 'Podłącz swoje Urządzenie',
      'detectWaiting': 'Oczekiwanie na połączenie urządzenia...',
      'detectConnected': 'Urządzenie podłączone pomyślnie!',
      'processTitle': 'Stosowanie Skali Szarości',
      'processing': 'Przetwarzanie...',
      'start': 'Start',
      'successTitle': 'Sukces!',
      'successMessage': 'Tryb skali szarości włączony na twoim urządzeniu',
      'successDetail': 'Możesz teraz używać AppLimit z wyświetlaczem w skali szarości',
      'done': 'Gotowe',
      'appNotInstalled': 'Aplikacja nie jest zainstalowana',
      'installAppPrompt': 'Aplikacja AppLimit nie jest zainstalowana na Twoim urządzeniu. Czy chcesz ją zainstalować?',
      'cancel': 'Anuluj',
      'install': 'Zainstaluj',
    },
    'ru-RU': {
      'selectLanguage': 'Выберите язык',
      'appTitle': 'AppLimit - Контроллер Оттенков Серого',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'Контроллер Оттенков Серого',
      'initializing': 'Инициализация...',
      'setupTitle': 'Настройте ваше Устройство',
      'setupDescription': 'Следуйте этим шагам, чтобы включить отладку USB на вашем Android устройстве',
      'steps': 'Шаги:',
      'instructions': '1. Откройте Настройки на вашем телефоне\n2. Перейдите в О телефоне\n3. Нажмите на Номер сборки 7 раз\n4. Вернитесь в Настройки > Параметры разработчика\n5. Включите Отладку USB',
      'watchTutorial': 'Смотреть Видео Урок',
      'continue': 'Продолжить',
      'detectTitle': 'Подключите ваше Устройство',
      'detectWaiting': 'Ожидание подключения устройства...',
      'detectConnected': 'Устройство успешно подключено!',
      'processTitle': 'Применение Оттенков Серого',
      'processing': 'Обработка...',
      'start': 'Старт',
      'successTitle': 'Успешно!',
      'successMessage': 'Режим оттенков серого включен на вашем устройстве',
      'successDetail': 'Теперь вы можете использовать AppLimit с дисплеем в оттенках серого',
      'done': 'Готово',
      'appNotInstalled': 'Приложение не установлено',
      'installAppPrompt': 'Приложение AppLimit не установлено на вашем устройстве. Хотите установить его?',
      'cancel': 'Отмена',
      'install': 'Установить',
    },
    'ja-JP': {
      'selectLanguage': '言語を選択',
      'appTitle': 'AppLimit - グレースケールコントローラー',
      'splashTitle': 'AppLimit',
      'splashSubtitle': 'グレースケールコントローラー',
      'initializing': '初期化中...',
      'setupTitle': 'デバイスをセットアップ',
      'setupDescription': 'これらの手順に従って、Androidデバイスでのusb デバッグを有効にしてください',
      'steps': '手順:',
      'instructions': '1. 電話機で設定を開く\n2. 電話機について に移動\n3. ビルド番号 を7回タップ\n4. 設定 > 開発者向けオプション に戻る\n5. USBデバッグ を有効にする',
      'watchTutorial': 'ビデオチュートリアルを見る',
      'continue': '続ける',
      'detectTitle': 'デバイスを接続',
      'detectWaiting': 'デバイス接続を待っています...',
      'detectConnected': 'デバイスが正常に接続されました！',
      'processTitle': 'グレースケールを適用中',
      'processing': '処理中...',
      'start': '開始',
      'successTitle': '成功しました！',
      'successMessage': 'デバイスでグレースケールモードが有効になりました',
      'successDetail': 'グレースケールディスプレイでAppLimitを使用できるようになりました',
      'done': '完了',
      'appNotInstalled': 'アプリがインストールされていません',
      'installAppPrompt': 'AppLimitアプリはデバイスにインストールされていません。インストールしますか？',
      'cancel': 'キャンセル',
      'install': 'インストール',
    },
    'zh-CN': {
      'selectLanguage': '选择语言',
      'appTitle': 'AppLimit - 灰度控制器',
      'splashTitle': 'AppLimit',
      'splashSubtitle': '灰度控制器',
      'initializing': '初始化中...',
      'setupTitle': '设置您的设备',
      'setupDescription': '按照以下步骤在您的Android设备上启用USB调试',
      'steps': '步骤：',
      'instructions': '1. 在手机上打开设置\n2. 进入关于手机\n3. 点击版本号7次\n4. 返回设置 > 开发者选项\n5. 启用USB调试',
      'watchTutorial': '观看视频教程',
      'continue': '继续',
      'detectTitle': '连接您的设备',
      'detectWaiting': '等待设备连接...',
      'detectConnected': '设备连接成功！',
      'processTitle': '应用灰度',
      'processing': '处理中...',
      'start': '开始',
      'successTitle': '成功！',
      'successMessage': '您的设备上已启用灰度模式',
      'successDetail': '现在您可以使用灰度显示的AppLimit',
      'done': '完成',
      'appNotInstalled': '应用未安装',
      'installAppPrompt': 'AppLimit应用未在您的设备上安装。您想安装它吗？',
      'cancel': '取消',
      'install': '安装',
    },
    'ko-KR': {
      'selectLanguage': '언어 선택',
      'appTitle': 'AppLimit - 그레이스케일 컨트롤러',
      'splashTitle': 'AppLimit',
      'splashSubtitle': '그레이스케일 컨트롤러',
      'initializing': '초기화 중...',
      'setupTitle': '기기 설정',
      'setupDescription': '다음 단계에 따라 Android 기기에서 USB 디버깅을 활성화하세요',
      'steps': '단계:',
      'instructions': '1. 휴대전화에서 설정 열기\n2. 휴대전화 정보로 이동\n3. 빌드 번호를 7번 탭\n4. 설정 > 개발자 옵션으로 돌아가기\n5. USB 디버깅 활성화',
      'watchTutorial': '비디오 튜토리얼 보기',
      'continue': '계속',
      'detectTitle': '기기 연결',
      'detectWaiting': '기기 연결 대기 중...',
      'detectConnected': '기기가 성공적으로 연결되었습니다!',
      'processTitle': '그레이스케일 적용 중',
      'processing': '처리 중...',
      'start': '시작',
      'successTitle': '성공!',
      'successMessage': '기기에서 그레이스케일 모드가 활성화되었습니다',
      'successDetail': '이제 그레이스케일 디스플레이로 AppLimit을 사용할 수 있습니다',
      'done': '완료',
      'appNotInstalled': '앱이 설치되지 않음',
      'installAppPrompt': 'AppLimit 앱이 기기에 설치되어 있지 않습니다. 설치하시겠습니까?',
      'cancel': '취소',
      'install': '설치',
    },
  };

  static void setLanguage(String lang) {
    if (_translations.containsKey(lang)) {
      _currentLanguage = lang;
    } else {
      // Try to match language code only (e.g., 'he' from 'he-IL')
      final langCode = lang.split('-').first;
      final matchingKey = _translations.keys.firstWhere(
        (key) => key.startsWith(langCode),
        orElse: () => 'en-US',
      );
      _currentLanguage = matchingKey;
    }
  }

  static void detectSystemLanguage() {
    final locale = Platform.localeName; // e.g., 'en_US', 'he_IL'
    final normalizedLocale = locale.replaceAll('_', '-'); // 'en-US', 'he-IL'
    setLanguage(normalizedLocale);
  }

  static String get(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['en-US']?[key] ?? key;
  }

  static String getCurrentLanguage() => _currentLanguage;
  
  static List<String> getSupportedLanguages() => _translations.keys.toList();
  
  static String getLanguageName(String langCode) {
    // Show language names in their own language
    const languageNames = {
      'en-US': 'English',
      'he-IL': 'עברית',
      'ar-AE': 'العربية',
      'es-ES': 'Español',
      'fr-FR': 'Français',
      'de-DE': 'Deutsch',
      'it-IT': 'Italiano',
      'pt-BR': 'Português',
      'pl-PL': 'Polski',
      'ru-RU': 'Русский',
      'ja-JP': '日本語',
      'zh-CN': '中文',
      'ko-KR': '한국어',
    };
    return languageNames[langCode] ?? langCode;
  }
  
  static String translate(String key) {
    return get(key);
  }
}
